### PR TITLE
Add fastest way to coijoin ubuntu guide

### PR DESCRIPTION
**Pull request by clay-v**

### CODE REVIEW

**Comment by clay-v** [comment]
@keblek @openoms
This is a summary of the steps I followed to in the tests I had time to do.

**Comment by openoms** [comment]
looks good. 
It is actually good to use `joinmarket` as the only extra user just need to keep in mind that the password will change to the default `joininbox` when running the `build_joininbox.sh`

**Comment by clay-v** [comment]
If I understand you correctly, @openoms , it's better put down `joinmarket` as the username when creating the Ubuntu user?

**Comment by openoms** [comment]
yes, in that case there will be no other user left with an unhandled password.

**Pull request merged**
